export const ingredients = [
  { label: "Flour", value: "Flour" },
  { label: "Eggs", value: "Eggs" },
  { label: "Milk", value: "Milk" },
  { label: "Sugar", value: "Sugar" },
  { label: "Butter", value: "Butter" },
  { label: "Salt", value: "Salt" },
  { label: "Yeast", value: "Yeast" },
  { label: "Baking powder", value: "Baking powder" },
  { label: "Chocolate chips", value: "Chocolate chips" },
  { label: "Vanilla extract", value: "Vanilla extract" },
  { label: "Ghee", value: "Ghee" },
  { label: "Mustard oil", value: "Mustard oil" },
  { label: "Turmeric powder", value: "Turmeric powder" },
  { label: "Chili powder", value: "Chili powder" },
  { label: "Cumin seeds", value: "Cumin seeds" },
  { label: "Coriander seeds", value: "Coriander seeds" },
  { label: "Garlic", value: "Garlic" },
  { label: "Ginger", value: "Ginger" },
  { label: "Onions", value: "Onions" },
  { label: "Tomatoes", value: "Tomatoes" },
  { label: "Potatoes", value: "Potatoes" },
  { label: "Chickpeas", value: "Chickpeas" },
  { label: "Lentils", value: "Lentils" },
  { label: "Rice", value: "Rice" },
  { label: "Fish", value: "Fish" },
  { label: "Chicken", value: "Chicken" },
  { label: "Beef", value: "Beef" },
  { label: "Yogurt", value: "Yogurt" },
  { label: "Lime juice", value: "Lime juice" },
  { label: "Coconut milk", value: "Coconut milk" },
  { label: "Bananas", value: "Bananas" },
  { label: "Mangoes", value: "Mangoes" },
  { label: "Panch Phoron", value: "Panch Phoron" },
  { label: "Bay leaves", value: "Bay leaves" },
  { label: "Green chilies", value: "Green chilies" },
  { label: "Cilantro", value: "Cilantro" },
  { label: "Mint leaves", value: "Mint leaves" },
  { label: "Shrimp", value: "Shrimp" },
  { label: "Hilsa fish", value: "Hilsa fish" },
  { label: "Begun", value: "Begun" },
  { label: "Aloo", value: "Aloo" },
  { label: "Doi", value: "Doi" },
];
